# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'OneSignalNotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalNotificationServiceExtension
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

end

target 'OneSignalTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneSignalTest
  pod 'OneSignal', '>= 2.6.2', '< 3.0'

  target 'OneSignalTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneSignalTestUITests' do
    # Pods for testing
  end

end
